In [1]:
from vrppd_parameters import parameters
from vrppd_solution import solution
import numpy as np
import is_feasible
import read_data
print(dir(read_data))
all_instances = read_data.read_all_instances_from_folder('Challenge/training_data_small')

# Quick Test to see whether parameters, solution and is_feasible work

test_parameters = parameters(all_instances[1])
test_solution = solution(test_parameters)

print(test_parameters)
print(test_solution)

test_solution.routing_plan = np.array([[1,-1]])
test_solution.delivery_assigned_courier[0] = 1
test_solution.delivery_count_assigned_to_courier[0] = 1
test_solution.delivery_delivery_time[0] = 35
test_solution.total_delivery_time = 35
print(test_parameters.delivery_count)
#is_feasible.is_feasible(test_parameters, test_solution)

ImportError: cannot import name 'parameters' from 'vrppd_parameters' (/Users/williambitsch/git/co-work2024-code-challenge/vrppd_parameters.py)

In [3]:
print(test_parameters.location_nearest_location_matrix)
print(test_parameters.location_nearest_delivery_matrix)

[[2 1]
 [2 0]
 [1 0]]
[[1]
 [1]
 [1]]


In [5]:
all_instances = read_data.read_all_instances_from_folder('Challenge/training_data')

Processing instance: 1d7c5373-e121-4d33-8dac-32f8801f7b6a
Processing instance: 3540d0d3-4667-444b-8700-1612f951c049
Processing instance: 4f90ea3a-aee4-4a3e-a862-c073e5390801
Processing instance: 6ed67a32-bfb7-4207-8873-6e0740467db5
Processing instance: 99a03a35-ab56-4bd8-8b1d-42a7f51969c8
Processing instance: 9ca9e06e-e1ce-4a05-b847-c1b0ecdd5e29
Processing instance: 16a60115-053d-4102-b189-1d2e1b2164a5
Processing instance: 49ecb4a1-ebdf-4826-836b-e02698de07fa
Processing instance: 4845b3e3-1ff2-44c2-9c0c-50874d4fab5b
Processing instance: a1e08921-ab7f-418d-b140-7034983c387a
Processing instance: 8c0c8ce3-bc0c-4422-9370-d8dcc45bdf7f
Processing instance: 9c1ad818-ec6f-4fd0-a1cb-485b6da0c22c
Processing instance: 5d8f0aa5-8639-476b-a314-f2bab5232403
Processing instance: b5d9b099-6e8a-4c2b-a11c-8db444257ab1
Processing instance: 1adef166-1111-45fd-b722-0f817c7fa055
Processing instance: 13346e71-0380-4feb-945a-2688f3dbd41b
Processing instance: 59d81edb-ec52-4bd4-9c4b-d771a234e88b
Processing ins

In [1]:
import numpy as np
import matplotlib.pyplot as plt

instance_sizes = [(len(instance['couriers']), len(instance['deliveries']), instance['instance_name']) for instance in all_instances]
#print(instance_sizes)

sorted_instance_sizes = sorted(instance_sizes, key=lambda x: x[0] / [1])
print(sorted_instance_sizes)

plt.plot([x[0] for x in sorted_instance_sizes], [x[1] for x in sorted_instance_sizes], 'o', markersize=3)

# Calculate the regression line
regression_line = np.polyfit([x[0] for x in sorted_instance_sizes], [x[1] for x in sorted_instance_sizes], 1)
x_values = [x[0] for x in sorted_instance_sizes]
y_values = np.polyval(regression_line, x_values)

# Plot the regression line
plt.plot(x_values, y_values, 'r-', label='Linear Regression')

# Linear regression equation
slope = regression_line[0]
intercept = regression_line[1]
equation = f'y = {slope:.2f}x + {intercept:.2f}'
plt.text(0.05, 0.95, equation, transform=plt.gca().transAxes)

# Rest of the code
plt.xlabel('Number of couriers')
plt.ylabel('Number of deliveries')
plt.title('Instance sizes')
plt.legend()
plt.show()


NameError: name 'all_instances' is not defined

[[0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]]
